# Generated by Django 5.0.1 on 2025-11-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='prodcut',
            new_name='product',
        ),
    ]
